-- =============================================================================
-- MaalRise — production database setup, PART 4 OF 4 (security, alerts, reference data).
--
-- FOR THE BROWSER-ONLY DEPLOY PATH. The Supabase SQL Editor refuses one big
-- paste, so the schema ships as four files. On a FRESH project, paste and Run
-- each part in order: part 1, then 2, then 3, then 4. Each part depends on the
-- ones before it and runs in a few seconds.
--
--   * Fresh project only — the parts are not written to upgrade a database
--     that already has the schema. If a part fails halfway, delete the
--     Supabase project and start again from part 1.
--   * No demo data, no accounts. (Never run supabase/seed.sql in production.)
--   * Part 4 ends with a NOTICE about the storage bucket on hosted Supabase:
--     that is expected — create the "documents" bucket and its four policies
--     through the dashboard, as the deployment guide shows.
--
-- Together the four parts are every migration in supabase/migrations/, in
-- order — the same schema the CLI's `supabase db push` would apply.
--
-- Generated by scripts/build-production-setup.sh — do not edit by hand.
-- =============================================================================


-- ═══ 20250101000600_rls.sql ═══

-- =============================================================================
-- Migration 0007 — Row Level Security
-- Every table has RLS. The Auditor is SELECT-only everywhere. Financial rows
-- are never hard-deleted, so DELETE is granted almost nowhere.
-- =============================================================================

do $$
declare
  t text;
  -- Tables any signed-in staff member (except the auditor) may maintain.
  ops_tables text[] := array[
    'suppliers', 'products', 'warehouses', 'businesses',
    'procurement_orders', 'procurement_items', 'shipments', 'shipment_costs',
    'goods_receipts', 'goods_receipt_items', 'inventory_lots', 'inventory_movements',
    'murabaha_sales', 'murabaha_sale_items', 'documents'
  ];
  -- Tables restricted to the CEO and the Accounts Officer.
  finance_tables text[] := array[
    'investors', 'investor_subscriptions', 'bank_accounts', 'cash_transactions',
    'supplier_payments', 'repayments', 'repayment_allocations', 'expenses',
    'expense_categories', 'other_assets', 'monthly_closings', 'investor_reports',
    'annual_closings', 'annual_closing_allocations', 'approvals'
  ];
  -- Tables only the CEO may change.
  ceo_tables text[] := array[
    'system_settings', 'user_roles', 'investment_cycles'
  ];
  all_tables text[];
begin
  all_tables := ops_tables || finance_tables || ceo_tables
                || array['profiles', 'notifications', 'audit_logs', 'document_sequences'];

  foreach t in array all_tables loop
    execute format('alter table %I enable row level security', t);
  end loop;

  -- Read access: every authenticated user holding any role, including the auditor.
  foreach t in array all_tables loop
    execute format(
      'create policy "read_all_roles" on %I for select to authenticated
       using (auth_role() is not null)', t);
  end loop;

  foreach t in array ops_tables loop
    execute format(
      'create policy "ops_insert" on %I for insert to authenticated
       with check (has_role(''ceo'', ''operations'', ''accounts''))', t);
    execute format(
      'create policy "ops_update" on %I for update to authenticated
       using (has_role(''ceo'', ''operations'', ''accounts''))
       with check (has_role(''ceo'', ''operations'', ''accounts''))', t);
  end loop;

  foreach t in array finance_tables loop
    execute format(
      'create policy "finance_insert" on %I for insert to authenticated
       with check (has_role(''ceo'', ''accounts''))', t);
    execute format(
      'create policy "finance_update" on %I for update to authenticated
       using (has_role(''ceo'', ''accounts''))
       with check (has_role(''ceo'', ''accounts''))', t);
  end loop;

  foreach t in array ceo_tables loop
    execute format(
      'create policy "ceo_insert" on %I for insert to authenticated
       with check (is_ceo())', t);
    execute format(
      'create policy "ceo_update" on %I for update to authenticated
       using (is_ceo()) with check (is_ceo())', t);
  end loop;

  -- Deletes are permitted only where nothing financial is destroyed.
  foreach t in array array['documents', 'notifications', 'procurement_items',
                           'goods_receipt_items', 'murabaha_sale_items'] loop
    execute format(
      'create policy "ceo_delete" on %I for delete to authenticated using (is_ceo())', t);
  end loop;
end;
$$;

-- Drafts are the one case where an operations user may remove their own line
-- items; everything approved is protected by the RPCs and status checks.
create policy "ops_delete_draft_items" on procurement_items
for delete to authenticated
using (
  has_role('ceo', 'operations', 'accounts')
  and exists (
    select 1 from procurement_orders po
    where po.id = procurement_order_id
      and po.status in ('draft', 'awaiting_approval')
  )
);

-- Profiles: everyone reads, users maintain their own, the CEO maintains all.
create policy "profile_self_update" on profiles
for update to authenticated
using (id = auth.uid() or is_ceo())
with check (id = auth.uid() or is_ceo());

create policy "profile_insert" on profiles
for insert to authenticated
with check (id = auth.uid() or is_ceo());

-- Notifications may be marked read by any signed-in user.
create policy "notifications_update" on notifications
for update to authenticated
using (auth_role() is not null)
with check (auth_role() is not null);

create policy "notifications_insert" on notifications
for insert to authenticated
with check (can_write());

-- audit_logs deliberately has NO insert, update or delete policy. Rows are
-- written by the SECURITY DEFINER audit trigger and can never be altered or
-- removed from the application (brief §25).

-- ---------------------------------------------------------------------------
-- Storage: a single private bucket for all uploaded evidence.
--
-- On hosted Supabase the storage tables are owned by the platform, so a
-- migration (or the SQL Editor) may not be permitted to create the bucket or
-- its policies. That is expected: the guarded block below applies them where
-- it can (local development, self-hosted) and otherwise raises a NOTICE, and
-- the deployment guide creates the same bucket and four policies through the
-- dashboard UI, which is the platform-supported path.
-- ---------------------------------------------------------------------------
do $$
begin
  insert into storage.buckets (id, name, public, file_size_limit)
  values ('documents', 'documents', false, 26214400)
  on conflict (id) do nothing;

  create policy "documents_read" on storage.objects
  for select to authenticated
  using (bucket_id = 'documents' and auth_role() is not null);

  create policy "documents_write" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'documents' and can_write());

  create policy "documents_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'documents' and can_write());

  create policy "documents_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'documents' and is_ceo());
exception
  when insufficient_privilege or undefined_table then
    raise notice 'Storage bucket/policies not applied here (%). Create the "documents" bucket and its four policies in the Supabase dashboard instead — see docs/DEPLOYMENT.md.', sqlerrm;
end;
$$;


-- ═══ 20250101000700_derived.sql ═══

-- =============================================================================
-- Migration 0008 — Derived totals
-- Line and header totals are computed in the database so that a client can
-- never post an internally inconsistent order.
-- =============================================================================

create or replace function sync_procurement_item_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rate numeric(18, 6);
begin
  select exchange_rate into v_rate from procurement_orders where id = new.procurement_order_id;

  new.line_total_foreign := round(new.quantity * new.unit_price_foreign, 2);
  new.line_total_naira   := round(new.line_total_foreign * coalesce(v_rate, 1), 2);

  -- Keep landed cost meaningful before any direct costs have been added.
  if new.landed_cost_total = 0 or new.allocated_cost_naira = 0 then
    new.landed_cost_total    := new.line_total_naira + new.allocated_cost_naira;
    new.landed_cost_per_unit := case when new.quantity > 0
                                     then round(new.landed_cost_total / new.quantity, 2)
                                     else 0 end;
  end if;

  return new;
end;
$$;

create trigger trg_procurement_item_totals
before insert or update of quantity, unit_price_foreign on procurement_items
for each row execute function sync_procurement_item_totals();

create or replace function sync_procurement_order_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order uuid := coalesce(new.procurement_order_id, old.procurement_order_id);
begin
  update procurement_orders po
     set total_cost_foreign = coalesce(t.foreign_total, 0),
         total_cost_naira   = coalesce(t.naira_total, 0)
  from (
    select sum(line_total_foreign) as foreign_total,
           sum(line_total_naira)   as naira_total
    from procurement_items where procurement_order_id = v_order
  ) t
  where po.id = v_order;

  return coalesce(new, old);
end;
$$;

create trigger trg_procurement_order_totals
after insert or update or delete on procurement_items
for each row execute function sync_procurement_order_totals();

-- Re-price every line when the header exchange rate changes (only possible
-- while the order is still a draft).
create or replace function reprice_procurement_items()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.exchange_rate is distinct from old.exchange_rate then
    if old.status not in ('draft', 'awaiting_approval') then
      raise exception 'The exchange rate cannot be changed after a procurement order is approved.'
        using errcode = 'check_violation';
    end if;

    update procurement_items
       set line_total_naira     = round(line_total_foreign * new.exchange_rate, 2),
           landed_cost_total    = round(line_total_foreign * new.exchange_rate, 2) + allocated_cost_naira,
           landed_cost_per_unit = case when quantity > 0
                                       then round((round(line_total_foreign * new.exchange_rate, 2) + allocated_cost_naira) / quantity, 2)
                                       else 0 end
     where procurement_order_id = new.id;
  end if;

  return new;
end;
$$;

create trigger trg_procurement_reprice
after update of exchange_rate on procurement_orders
for each row execute function reprice_procurement_items();

-- Goods receipt lines: sellable = received − damaged − rejected.
create or replace function sync_goods_receipt_item()
returns trigger
language plpgsql
as $$
begin
  new.missing_quantity  := greatest(new.expected_quantity - new.quantity_received, 0);
  new.sellable_quantity := greatest(
    new.quantity_received - new.damaged_quantity - new.rejected_quantity, 0);

  if new.quantity_received > new.expected_quantity then
    raise exception 'Received quantity (%) exceeds the expected quantity (%).',
      new.quantity_received, new.expected_quantity
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

create trigger trg_goods_receipt_item_totals
before insert or update on goods_receipt_items
for each row execute function sync_goods_receipt_item();

-- Overdue Murabaha contracts are flagged by the daily job, never re-priced.
create or replace function flag_overdue_sales()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  update murabaha_sales
     set status = 'overdue'
   where status in ('active', 'partially_paid')
     and due_date < current_date
     and amount_paid < selling_price;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;


-- ═══ 20250101000800_status_rpc.sql ═══

-- =============================================================================
-- Migration 0009 — Status transitions and notification helpers
--
-- A status change and its audit reason must happen in ONE transaction: the
-- reason is carried in a transaction-local GUC that the audit trigger reads,
-- so setting it in a separate round trip would lose it.
-- =============================================================================

create or replace function change_record_status(
  p_table text,
  p_id uuid,
  p_status text,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_allowed constant text[] := array[
    'procurement_orders', 'shipments', 'goods_receipts', 'investment_cycles',
    'suppliers', 'businesses', 'investors', 'products', 'murabaha_sales'
  ];
  v_current text;
begin
  if not (p_table = any(v_allowed)) then
    raise exception 'Status changes are not permitted on %', p_table;
  end if;

  if p_reason is null or length(trim(p_reason)) < 3 then
    raise exception 'A reason is required; it is written to the audit trail.';
  end if;

  -- The cycle is the CEO's to steer; everything else is open to operating staff.
  if p_table = 'investment_cycles' then
    if not is_ceo() then
      raise exception 'Only the CEO may change the status of an investment cycle.';
    end if;
  elsif not can_write() then
    raise exception 'You do not have permission to change this record.';
  end if;

  perform set_audit_reason(p_reason);

  execute format('select status::text from %I where id = $1', p_table)
    into v_current using p_id;

  if v_current is null then
    raise exception 'Record not found';
  end if;

  -- An approved Murabaha contract is settled by repayments, not by hand.
  if p_table = 'murabaha_sales' and p_status in ('fully_paid', 'partially_paid') then
    raise exception 'Payment status is set by recording a repayment, not by editing the contract.';
  end if;

  -- A completed cycle is closed for good.
  if p_table = 'investment_cycles' and v_current = 'completed' then
    raise exception 'This cycle is completed and can no longer be changed.';
  end if;

  execute format('update %I set status = $1::%s where id = $2',
                 p_table,
                 case p_table
                   when 'procurement_orders' then 'procurement_status'
                   when 'shipments'          then 'shipment_status'
                   when 'goods_receipts'     then 'goods_receipt_status'
                   when 'investment_cycles'  then 'cycle_status'
                   when 'suppliers'          then 'supplier_status'
                   when 'businesses'         then 'business_status'
                   when 'investors'          then 'investor_status'
                   when 'products'           then 'product_status'
                   when 'murabaha_sales'     then 'murabaha_status'
                 end)
  using p_status, p_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------
create or replace function mark_notifications_read(p_ids uuid[] default null)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count int;
begin
  update notifications
     set is_read = true, read_at = now()
   where is_read = false
     and (p_ids is null or id = any(p_ids));

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- Daily jobs. Scheduled with pg_cron where the extension is available; the
-- app also exposes them through /api/cron for platforms without it.
-- ---------------------------------------------------------------------------
create or replace function run_daily_jobs()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_alerts int;
  v_overdue int;
begin
  v_overdue := flag_overdue_sales();
  v_alerts := generate_alerts();

  -- Cycles within 60 days of maturity are flagged for the closing process.
  update investment_cycles
     set status = 'approaching_maturity'
   where status = 'active'
     and maturity_date <= current_date + 60;

  update investment_cycles
     set status = 'matured'
   where status in ('active', 'approaching_maturity')
     and maturity_date <= current_date;

  return jsonb_build_object('alerts_created', v_alerts, 'sales_flagged_overdue', v_overdue);
end;
$$;

do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule('maalrise-daily-jobs', '0 6 * * *', 'select run_daily_jobs()');
  end if;
exception when others then
  raise notice 'pg_cron not scheduled: %. Use the /api/cron route instead.', sqlerrm;
end;
$$;


-- ═══ 20250101000900_reference_data.sql ═══

-- =============================================================================
-- Migration 0010 — Reference data
--
-- Settings and expense categories are configuration the application needs in
-- order to run at all, not sample data: without them investor validation has no
-- unit price, reports have no branding, and no expense can be classified.
--
-- They live in a migration rather than in seed.sql so that `supabase db push`
-- against production yields a working system. seed.sql is demo data only, and
-- must never be run against production — it creates staff accounts with a
-- password published in this repository.
--
-- Every statement is idempotent, so re-running a push is safe.
-- =============================================================================

-- System settings (brief §28) — nothing configurable is hardcoded in the app.
-- ---------------------------------------------------------------------------
insert into system_settings (key, value, value_type, label, category, description) values
  ('company.name',              '"MaalRise"',                            'string',  'Company name',              'branding',    'Displayed across the app and on reports'),
  ('company.platform',          '"Maalvest Investment Limited"',         'string',  'Platform',                  'branding',    'Legal entity operating MaalRise'),
  ('company.address',           '"Abuja, Nigeria"',                      'string',  'Registered address',        'branding',    null),
  ('company.email',             '"info@maalrise.com"',                   'string',  'Contact email',             'branding',    null),
  ('company.phone',             '"+234 800 000 0000"',                   'string',  'Contact phone',             'branding',    null),
  ('company.logo_url',          '""',                                    'string',  'Logo URL',                  'branding',    'Shown on reports and in the app header'),
  ('company.currency',          '"NGN"',                                 'string',  'Reporting currency',        'finance',     'All reporting is in Naira'),
  ('investor.unit_price',       '100000',                                'number',  'Price per unit (₦)',        'investors',   'One investment unit'),
  ('investor.min_units_new',    '5',                                     'number',  'Minimum units — new investor',     'investors', null),
  ('investor.min_units_current','1',                                     'number',  'Minimum units — current investor', 'investors', null),
  ('profit.investor_share',     '0.7',                                   'number',  'Investor profit share',     'finance',     'Share of net profit allocated to investors at cycle close'),
  ('expense.approval_limit',    '250000',                                'number',  'Expense approval limit (₦)','approvals',   'Expenses above this amount require approval'),
  ('procurement.approval_limit','0',                                     'number',  'Procurement approval limit (₦)', 'approvals', 'Zero means every procurement order requires approval'),
  ('murabaha.default_repayment_days', '45',                              'number',  'Default repayment period (days)', 'finance', 'Roughly one and a half months'),
  ('murabaha.default_markup',   '0.15',                                  'number',  'Default Murabaha markup',   'finance',     'Applied as cost × markup'),
  ('cycle.default_duration_months', '12',                                'number',  'Default cycle duration (months)', 'finance', null),
  ('numbering.procurement',     '"MR-PO"',                               'string',  'Procurement prefix',        'numbering',   null),
  ('numbering.murabaha',        '"MR-MUR"',                              'string',  'Murabaha prefix',           'numbering',   null),
  ('numbering.shipment',        '"MR-SHP"',                              'string',  'Shipment prefix',           'numbering',   null),
  ('numbering.goods_receipt',   '"MR-GRN"',                              'string',  'Goods receipt prefix',      'numbering',   null),
  ('numbering.repayment',       '"MR-RCP"',                              'string',  'Repayment prefix',          'numbering',   null),
  ('numbering.expense',         '"MR-EXP"',                              'string',  'Expense prefix',            'numbering',   null),
  ('notifications.due_soon_days', '7',                                   'number',  'Alert lead time (days)',    'notifications', null),
  ('report.disclaimer',
   '"Monthly profit figures are provisional and provided for performance reporting purposes only. Final distributable profit will be determined after the completion of the 12-month investment cycle and the closing of the accounts. Investment returns are based on actual business performance and are not guaranteed."',
   'string', 'Investor report disclaimer', 'reports', 'Printed on every monthly investor report')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------------
-- Expense categories (brief §19). Direct costs are capitalised into landed
-- cost and are therefore excluded from operating expenses in the P&L.
-- ---------------------------------------------------------------------------
insert into expense_categories (name, code, is_direct_cost) values
  ('Procurement',           'procurement',        true),
  ('Shipping',              'shipping',           true),
  ('Clearing',              'clearing',           true),
  ('Customs',               'customs',            true),
  ('Insurance',             'insurance',          true),
  ('Port charges',          'port_charges',       true),
  ('Local logistics',       'local_logistics',    true),
  ('Storage',               'storage',            false),
  ('Staff salaries',        'staff_salaries',     false),
  ('Professional fees',     'professional_fees',  false),
  ('Software',              'software',           false),
  ('Bank charges',          'bank_charges',       false),
  ('Foreign exchange charges', 'fx_charges',      false),
  ('Marketing',             'marketing',          false),
  ('Office expenses',       'office_expenses',    false),
  ('Legal and compliance',  'legal_compliance',   false),
  ('Miscellaneous',         'miscellaneous',      false)
on conflict (code) do nothing;



-- ═══ 20250101001000_auth_profile.sql ═══

-- =============================================================================
-- Migration 0011 — Profile creation on sign-up
--
-- `profiles` holds the staff details the application reads; `auth.users` holds
-- the credentials. Nothing connected the two, so a person invited through
-- Supabase Auth had no profile row and the Users page could not see them.
--
-- This trigger creates the profile automatically. It deliberately does NOT
-- grant a role: a new account can authenticate but every read policy requires
-- `auth_role()` to return something, so the account sees nothing at all until
-- the CEO assigns a role on the Users page. Access stays a decision someone
-- makes, not a side effect of signing up.
-- =============================================================================

create or replace function handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    -- Supabase puts an invited user's name in raw_user_meta_data when the
    -- inviter supplies one; fall back to the local part of their address.
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
      initcap(replace(split_part(new.email, '@', 1), '.', ' '))
    ),
    new.email
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function handle_new_auth_user();
