#!/usr/bin/env bash
# Regenerates supabase/production_setup.sql — the single file a browser-only
# deploy pastes into the Supabase SQL Editor. Run this after adding or editing
# any migration, and commit the result.
set -euo pipefail
cd "$(dirname "$0")/.."

out=supabase/production_setup.sql
{
  cat <<'HEADER'
-- =============================================================================
-- MaalRise — complete production database setup, in one file.
--
-- FOR THE BROWSER-ONLY DEPLOY PATH. Paste this entire file into the Supabase
-- SQL Editor of a FRESH project and click Run once. It is every migration in
-- supabase/migrations/, concatenated in order — the same schema the CLI's
-- `supabase db push` would apply.
--
--   * Run it on a fresh project only. It is not written to upgrade a database
--     that already has the schema.
--   * It contains NO demo data and creates NO accounts. (Never run
--     supabase/seed.sql against production.)
--   * A NOTICE about the storage bucket at the end is expected on hosted
--     Supabase: create the "documents" bucket and its four policies through
--     the dashboard, as the deployment guide shows.
--
-- Generated by scripts/build-production-setup.sh — do not edit by hand.
-- =============================================================================
HEADER
  for f in supabase/migrations/*.sql; do
    printf '\n\n-- ═══ %s ═══\n\n' "$(basename "$f")"
    cat "$f"
  done
} > "$out"

echo "wrote $out ($(wc -l < "$out") lines from $(ls supabase/migrations/*.sql | wc -l) migrations)"
