#!/usr/bin/env bash
# Regenerates supabase/production_setup_part1..4.sql — the files a browser-only
# deploy pastes into the Supabase SQL Editor, one after the other, in order.
#
# Why parts: the Supabase SQL Editor refuses very large pastes with
# "Query is too large to be run via the SQL Editor". The full schema is ~177 KB,
# which is over that limit, so it ships as four parts of at most ~55 KB each.
# Together they are every migration in supabase/migrations/, concatenated in
# order — the same schema the CLI's `supabase db push` would apply.
#
# Run this after adding or editing any migration, and commit the result.
set -euo pipefail
cd "$(dirname "$0")/.."

# Migration groups, one per part. Order inside each group and across groups
# must match the filename order of supabase/migrations/.
part1="20250101000000_enums.sql 20250101000100_tables.sql"
part2="20250101000200_functions.sql 20250101000300_rpcs.sql"
part3="20250101000400_views.sql 20250101000500_closings.sql"
part4="20250101000600_rls.sql 20250101000700_derived.sql 20250101000800_status_rpc.sql 20250101000900_reference_data.sql 20250101001000_auth_profile.sql"

titles=(
  "types and tables"
  "core functions and financial RPCs"
  "reporting views and closings"
  "security, alerts, reference data"
)

# Safety: every migration file must appear in exactly one part.
listed=$(printf '%s\n' $part1 $part2 $part3 $part4 | sort)
actual=$(ls supabase/migrations/*.sql | xargs -n1 basename | sort)
if [ "$listed" != "$actual" ]; then
  echo "ERROR: migration list in this script is out of date." >&2
  diff <(echo "$listed") <(echo "$actual") >&2 || true
  exit 1
fi

rm -f supabase/production_setup.sql   # superseded single-file build

n=0
for group in "$part1" "$part2" "$part3" "$part4"; do
  n=$((n + 1))
  out="supabase/production_setup_part${n}.sql"
  {
    cat <<HEADER
-- =============================================================================
-- MaalRise — production database setup, PART ${n} OF 4 (${titles[$((n-1))]}).
--
-- FOR THE BROWSER-ONLY DEPLOY PATH. The Supabase SQL Editor refuses one big
-- paste, so the schema ships as four files. On a FRESH project, paste and Run
-- each part in order: part 1, then 2, then 3, then 4. Each part depends on the
-- ones before it and runs in a few seconds.
--
--   * Fresh project only — the parts are not written to upgrade a database
--     that already has the schema. If a part fails halfway, delete the
--     Supabase project and start again from part 1.
--   * No demo data, no accounts. (Never run supabase/seed.sql in production.)
--   * Part 4 ends with a NOTICE about the storage bucket on hosted Supabase:
--     that is expected — create the "documents" bucket and its four policies
--     through the dashboard, as the deployment guide shows.
--
-- Together the four parts are every migration in supabase/migrations/, in
-- order — the same schema the CLI's \`supabase db push\` would apply.
--
-- Generated by scripts/build-production-setup.sh — do not edit by hand.
-- =============================================================================
HEADER
    for f in $group; do
      printf '\n\n-- ═══ %s ═══\n\n' "$f"
      cat "supabase/migrations/$f"
    done
  } > "$out"
  echo "wrote $out ($(wc -c < "$out") bytes, $(wc -l < "$out") lines)"
done
